### ISSUE TITLE
[Az.MarketplaceOrdering] margtion sdk cmdlet to auto generate cmdlet.

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#19]
- [x] replace management sdk
- [x] Add upcomming change in management cmdlet.
- [ ] https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

**Comment by LucasYao93** [comment]
BreakChangeMessage attribute:
https://github.com/Azure/azure-powershell/pull/14650/files#diff-2731868b4c45415d73cf775ff5413935bc9abe60ffaf719a5e00c785160b3959

**Comment by LucasYao93** [comment]
```powershell
Get-AzMarketplaceTerms -Publisher "microsoft-ads" -Product "windows-data-science-vm" -Name "windows2016" -Debug

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/microsoft-ads/offers/windows-data-science-vm/plans/windows2016/agreements/current?api-version=2015-06-01

Headers:
x-ms-client-request-id        : 4e5b41e7-e8f1-4357-8e3b-48385423b2c8
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Vary                          : Accept-Encoding
X-Frame-Options               : SAMEORIGIN
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-request-id               : 947991f1-60b2-4f09-bda4-32022e016aa6
x-ms-correlation-request-id   : 947991f1-60b2-4f09-bda4-32022e016aa6
x-ms-routing-request-id       : SOUTHEASTASIA:20220816T084158Z:947991f1-60b2-4f09-bda4-32022e016aa6
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 16 Aug 2022 08:41:57 GMT

Body:
{
  "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/offerTypes/VirtualMachine/publishers/microsoft-ads/offers/windows-data-science-vm/plans/windows2016/agreements/current",
  "name": "windows2016",
  "type": "Microsoft.MarketplaceOrdering/offertypes",
  "properties": {
    "publisher": "microsoft-ads",
    "product": "windows-data-science-vm",
    "plan": "windows2016",
    "licenseTextLink": "https://mpcprodsa.blob.core.windows.net/legalterms/3E5ED_legalterms_MICROSOFT%253a2DADS%253a24WINDOWS%253a2DDATA%253a2DSCIENCE%253a2DVM%253a24WINDOWS2016%253a24T6KYYUE6UICDGSKJBSZ7NUG36TS7TLQNEXKVU5ZKR2Y2KZNYCHB3KPFZZIJSWAYBL3WOEYWIQZASGI2LEGBOM2MSVTDOBSREMDZG2DI.txt",
    "privacyPolicyLink": "https://www.microsoft.com/EN-US/privacystatement/OnlineServices/Default.aspx",
    "retrieveDatetime": "2022-08-16T08:41:58.7036433Z",
    "signature": "SUBEBHAL7CKDFJ2LMEFRQW3MEVI55JGU3GMGE4QDLD3HXOKLUBD6LGJBCEA5CG4X2CSP3P73NLJWZVEMV3PHP4WNO6IEJRUJY26EG4Q",
    "accepted": false
  }
}



Publisher         : microsoft-ads
Product           : windows-data-science-vm
Plan              : windows2016
LicenseTextLink   : https://mpcprodsa.blob.core.windows.net/legalterms/3E5ED_legalterms_MICROSOFT%253a2DADS%253a24WINDO
                    WS%253a2DDATA%253a2DSCIENCE%253a2DVM%253a24WINDOWS2016%253a24T6KYYUE6UICDGSKJBSZ7NUG36TS7TLQNEXKVU5
                    ZKR2Y2KZNYCHB3KPFZZIJSWAYBL3WOEYWIQZASGI2LEGBOM2MSVTDOBSREMDZG2DI.txt
PrivacyPolicyLink : https://www.microsoft.com/EN-US/privacystatement/OnlineServices/Default.aspx
Signature         : SUBEBHAL7CKDFJ2LMEFRQW3MEVI55JGU3GMGE4QDLD3HXOKLUBD6LGJBCEA5CG4X2CSP3P73NLJWZVEMV3PHP4WNO6IEJRUJY26
                    EG4Q
Accepted          : False
Signdate          : 8/16/2022 8:41:58 AM

DEBUG: 4:41:58 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent: Module: Az.MarketplaceOrdering:1.0.2; CommandName: Get-AzMarketplaceTerms; PSVersion: 7.2.5; IsSuccess: True; Duration: 00:00:03.5655590
DEBUG: Finish sending metric.
DEBUG: 4:41:59 PM - GetAzureRmMarketplaceTerms end processing.
```

**Comment by LucasYao93** [comment]
Old:
/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/microsoft-ads/offers/windows-data-science-vm/plans/windows2016/agreements/current?api-version=2015-06-01

New:
/subscriptions/{subscriptionId}/providers/Microsoft.MarketplaceOrdering/offerTypes/{offerType}/publishers/{publisherId}/offers/{offerId}/plans/{planId}/agreements/current?api-version=2021-01-01

**Comment by LucasYao93** [comment]
Below two API swagger will generate same variant of the same cmdlet. Because the offerType parameter in path that been defined x-ms-parameter-location.

![image](https://user-images.githubusercontent.com/53558334/184845372-5b209922-5363-4544-b4df-e00a106bc9b8.png)

(A) https://github.com/Azure/azure-rest-api-specs/blob/main/specification/marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering/stable/2021-01-01/Agreements.json#L37

(B )https://github.com/Azure/azure-rest-api-specs/blob/main/specification/marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering/stable/2021-01-01/Agreements.json#L249

**Comment by LucasYao93** [comment]
Get-AzMarketplaceTerms -Publisher "microsoft-ads" -Product "windows-data-science-vm" -Name "windows2016"

https://management.azure.com/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/microsoft-ads/offers/windows-data-science-vm/plans/windows2016/agreements/current?api-version=2015-06-01

Get-AzMarketplaceTerms -OfferType 'virtualmachine' -OfferId "windows-data-science-vm" -PublisherId "microsoft-ads" -PlanId "windows2016"

https://management.azure.com/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/microsoft-ads/offers/windows-data-science-vm/plans/windows2016/agreements/current?api-version=2021-01-01

**Comment by LucasYao93** [comment]
❌ 
 Get-AzMarketplaceTerms -Debug
DEBUG: 7:11:14 PM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements?api-version=2021-01-01
DEBUG: RequestCreated: /subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements?api-version=2021-01-01
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements?api-version=2021-01-01

Headers:
x-ms-unique-id                : 4
x-ms-client-request-id        : 6935f985-1438-40dd-bca9-c2ace9a44b63
CommandName                   : Get-AzMarketplaceTerms
FullCommandName               : Get-AzMarketplaceTerms_List
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v7.2.6,Az.MarketplaceOrdering/0.1.0

Body:



DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Vary                          : Accept-Encoding
X-Frame-Options               : SAMEORIGIN
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-request-id               : 9ff694d5-7998-4322-aee4-bb460101511c
x-ms-correlation-request-id   : 9ff694d5-7998-4322-aee4-bb460101511c
x-ms-routing-request-id       : SOUTHEASTASIA:20220823T111114Z:9ff694d5-7998-4322-aee4-bb460101511c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 23 Aug 2022 11:11:14 GMT

Body:
{
  "value": [
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/offers/barracuda_cloudgenwan/plans/saas_06_2020",
      "name": "saas_06_2020",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "barracudanetworks",
        "offer": "barracuda_cloudgenwan",
        "signDate": "2022-07-05T08:48:25.2878082Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/datadog1591740804488/offers/dd_liftr_v2/plans/payg_v2",
      "name": "payg_v2",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "datadog1591740804488",
        "offer": "dd_liftr_v2",
        "signDate": "2021-12-01T06:41:49.6127714Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/dynatrace/offers/dynatrace_portal_integration/plans/5gb14days7_1",
      "name": "5gb14days7_1",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "dynatrace",
        "offer": "dynatrace_portal_integration",
        "signDate": "2021-10-10T18:55:36.1698914Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/dynatrace/offers/dynatrace_portal_integration/plans/azureportalintegration",
      "name": "azureportalintegration",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "dynatrace",
        "offer": "dynatrace_portal_integration",
        "signDate": "2021-10-25T11:42:23.3166152Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/dynatrace/offers/dynatrace_portal_integration/plans/azureportalintegration_privatepreview",
      "name": "azureportalintegration_privatepreview",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "dynatrace",
        "offer": "dynatrace_portal_integration",
        "signDate": "2021-11-22T09:08:24.8959751Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/dynatrace/offers/dynatrace_portal_integration/plans/liftr_dynatrace_plan1",
      "name": "liftr_dynatrace_plan1",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "dynatrace",
        "offer": "dynatrace_portal_integration",
        "signDate": "2021-10-07T08:34:34.5578385Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/dynatrace/offers/dynatrace_portal_integration/plans/yearly",
      "name": "yearly",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "dynatrace",
        "offer": "dynatrace_portal_integration",
        "signDate": "2021-11-18T07:59:41.1609962Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/elastic/offers/ec-azure-pp/plans/ess-monthly-consumption",
      "name": "ess-monthly-consumption",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "elastic",
        "offer": "ec-azure-pp",
        "signDate": "2022-05-23T10:08:14.5803323Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/influxdata/offers/influxdb-cloud/plans/usage",
      "name": "usage",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "influxdata",
        "offer": "influxdb-cloud",
        "signDate": "2021-12-09T15:48:07.1957516Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/isvtestuklegacy/offers/lts_seat_test/plans/yonit_lts_seat_test4",
      "name": "yonit_lts_seat_test4",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "isvtestuklegacy",
        "offer": "lts_seat_test",
        "signDate": "2022-07-05T08:45:04.7345871Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/logz/offers/logzio_via_liftr/plans/100gb14days",
      "name": "100gb14days",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "logz",
        "offer": "logzio_via_liftr",
        "signDate": "2021-10-20T12:28:11.426263Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/logz/offers/logzio_via_liftr/plans/50gb14days_rubrik2",
      "name": "50gb14days_rubrik2",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "logz",
        "offer": "logzio_via_liftr",
        "signDate": "2021-11-18T05:23:20.1044098Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/mongodb/offers/mongodb_atlas_elastic_listing/plans/mdb_atlas_free_tier",
      "name": "mdb_atlas_free_tier",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "mongodb",
        "offer": "mongodb_atlas_elastic_listing",
        "signDate": "2022-07-05T08:59:44.6368391Z",
        "state": "Active"
      }
    },
    {
      "id": "/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/agreements/isvtestuklegacy/offers/liftr_dt_mpo_tst_prod/plans/monthly",
      "name": "monthly",
      "type": "Microsoft.MarketplaceOrdering/agreements",
      "properties": {
        "publisher": "isvtestuklegacy",
        "offer": "liftr_dt_mpo_tst_prod",
        "signDate": "2021-09-21T11:01:11.5101408Z",
        "state": "Active"
      }
    }
  ]
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
DEBUG: Finally: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: [CmdletException]: Received Exception with message 'InvalidCastException - Unable to cast object of type 'Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonObject' to type 'Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonArray'. :    at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonArray.Parse(String text) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\runtime\Nodes\Collections\JsonArray.cs:line 63       
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.<>c.<MarketplaceAgreementsList_Call>b__18_0(Task`1 body) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 858
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_List.onOk(HttpResponseMessage responseMessage, Task`1 response) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\cmdlets\GetAzMarketplaceTerms_List.cs:line 378
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.MarketplaceAgreementsList_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 858
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.MarketplaceAgreementsList_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 875
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.MarketplaceAgreementsList(String subscriptionId, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 778
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_List.ProcessRecordAsync() in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\cmdlets\GetAzMarketplaceTerms_List.cs:line 290
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_List.ProcessRecordAsync() in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\cmdlets\GetAzMarketplaceTerms_List.cs:line 304'        
DEBUG: CmdletException: InvalidCastException - Unable to cast object of type 'Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonObject' to type 'Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonArray'. :    at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonArray.Parse(String text) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\runtime\Nodes\Collections\JsonArray.cs:line 63
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.<>c.<MarketplaceAgreementsList_Call>b__18_0(Task`1 body) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 858
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_List.onOk(HttpResponseMessage responseMessage, Task`1 response) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\cmdlets\GetAzMarketplaceTerms_List.cs:line 378
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.MarketplaceAgreementsList_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 858
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.MarketplaceAgreementsList_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 875
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.MarketplaceOrdering.MarketplaceAgreementsList(String subscriptionId, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\api\MarketplaceOrdering.cs:line 778
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_List.ProcessRecordAsync() in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\cmdlets\GetAzMarketplaceTerms_List.cs:line 290
   at Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_List.ProcessRecordAsync() in D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\generated\cmdlets\GetAzMarketplaceTerms_List.cs:line 304
DEBUG: CmdletProcessRecordEnd: 
WARNING: Get-AzMarketplaceTerms_List is not found. The most similar Azure PowerShell command is:
        Get-AzMarketplaceTerms
Get-AzMarketplaceTerms_List: D:\repository\azure-powershell\generation\azure-powershell\src\MarketplaceOrdering\exports\ProxyCmdletDefinitions.ps1:787:9
Line |
 787 |          $steppablePipeline.Begin($PSCmdlet)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to cast object of type 'Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonObject' to type 'Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Runtime.Json.JsonArray'.

**Comment by LucasYao93** [comment]
# api version 2015-06-01
$agreementTerms = Get-AzMarketplaceTerms -Publisher "microsoft-ads" -Product "windows-data-science-vm" -Name "windows2016"
Set-AzMarketplaceTerms -Publisher "microsoft-ads" -Product "windows-data-science-vm" -Name "windows2016" -Terms $agreementTerms -Accept

# api version 2021-01-01
$agreementTerms = Get-AzMarketplaceTerms -Publisher "microsoft-ads" -Product "windows-data-science-vm" -Name "windows2016"
New-AzMarketplaceTerms -PublisheId "microsoft-ads" -OfferId"windows-data-science-vm" -PlanId"windows2016" -Accept

**Comment by LucasYao93** [comment]
# Point Record
## Get-AzMarketplaceTerms(2015-06-01)
Get-AzMarketplaceTerms -Publisher "microsoft-ads" -Product "windows-data-science-vm" -Name "windows2016" -Debug
https://management.azure.com/subscriptions/ce37d538-dfa3-49c3-b3cd-149b4b7db48a/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/microsoft-ads/offers/windows-data-science-vm/plans/windows2016/agreements/current?api-version=2015-06-01

**Comment by LucasYao93** [comment]
# Why rename New-AzMarketplaceTerms to Set-AzMarketplaceTerms
New-AzMarketplaceTerms  only support update terms and some properties.
